const internships = [
    {
        id: 1,
        company: "Google",
        title: "Frontend React Intern",
        location: "Noida",
        stipend: "₹20,000 / Month",
        duration: "6 Months",
        type: "Remote",
        skills: ["React", "JavaScript", "CSS", "HTML"],
    },
    {
        id: 2,
        company: "Microsoft",
        title: "Backend Intern",
        location: "Bangalore",
        stipend: "₹25,000 / Month",
        duration: "3 Months",
        type: "Hybrid",
        skills: ["Node.js", "Express", "MongoDB"],
    },
    {
        id: 3,
        company: "Amazon",
        title: "Full Stack Intern",
        location: "Hyderabad",
        stipend: "₹30,000 / Month",
        duration: "6 Months",
        type: "Work From Home",
        skills: ["React", "Node.js", "MongoDB"],
    },
    {
        id: 4,
        company: "Infosys",
        title: "Web Development Intern",
        location: "Pune",
        stipend: "₹15,000 / Month",
        duration: "4 Months",
        type: "On Site",
        skills: ["HTML", "CSS", "JavaScript"],
    },
    {
        id: 5,
        company: "TCS",
        title: "Software Engineer Intern",
        location: "Noida",
        stipend: "₹18,000 / Month",
        duration: "6 Months",
        type: "Hybrid",
        skills: ["Java", "SQL", "Git"],
    },
    {
        id: 6,
        company: "Wipro",
        title: "Frontend Intern",
        location: "Delhi",
        stipend: "₹16,000 / Month",
        duration: "3 Months",
        type: "Remote",
        skills: ["React", "Bootstrap", "JavaScript"],
    },
];

export default internships;