const workFromHomeJobs = [
    {
        id: 1,
        company: "Google",
        title: "Frontend React Developer",
        location: "Remote",
        salary: "₹8 - ₹12 LPA",
        experience: "1+ Years",
        type: "Full Time",
        skills: ["React", "JavaScript", "HTML", "CSS"],
    },
    {
        id: 2,
        company: "Microsoft",
        title: "Backend Node.js Developer",
        location: "Remote",
        salary: "₹10 - ₹16 LPA",
        experience: "2+ Years",
        type: "Full Time",
        skills: ["Node.js", "Express", "MongoDB"],
    },
    {
        id: 3,
        company: "Amazon",
        title: "UI / UX Designer",
        location: "Work From Home",
        salary: "₹7 - ₹10 LPA",
        experience: "Freshers",
        type: "Remote",
        skills: ["Figma", "Adobe XD", "Photoshop"],
    },
    {
        id: 4,
        company: "Infosys",
        title: "Web Developer",
        location: "Remote",
        salary: "₹5 - ₹8 LPA",
        experience: "1+ Years",
        type: "Hybrid",
        skills: ["HTML", "CSS", "JavaScript"],
    },
    {
        id: 5,
        company: "TCS",
        title: "React Developer",
        location: "Remote",
        salary: "₹6 - ₹9 LPA",
        experience: "Freshers",
        type: "Full Time",
        skills: ["React", "Redux", "REST API"],
    },
    {
        id: 6,
        company: "Wipro",
        title: "Frontend Developer",
        location: "Remote",
        salary: "₹4 - ₹7 LPA",
        experience: "0 - 1 Year",
        type: "Work From Home",
        skills: ["Bootstrap", "CSS", "JavaScript"],
    },
];

export default workFromHomeJobs;